### ISSUE TITLE
Suggestion: show extra attacks as part of stat

### ISSUE THREAD

**Issue by evilstreak** [Floppy/scriptorum#26]
If a unit has extra attacks from a specialism (combat) or weapon (chainsword, pair of lightning claws) then it would be nice to show them in the stat bubble. For example:

- for a veteran sergeant (base: 3 attacks) with a combat specialism, it could show "Attacks: 3+1"
- for a terminator (base: 2 attacks) with a pair of lightning claws, it could show "Attacks: 2+1"

For a unit that has multiple melee weapons, some of which grant extra attacks, this probably can't be done.

**Comment by Floppy** [comment]
Done! It adds on any potential extras, but it can't determine valid combinations, so it shows them as "+1" to remind you to check.
