### ISSUE TITLE
Error when adding roster by clicking

### ISSUE THREAD

**Issue by r4dian** [Floppy/scriptorum#3]
Google Chrome | 78.0.3904.97 (Official Build) (64-bit) (cohort: Stable)
OS | Windows 10 OS Version 1903 (Build 18362.476)

log & roster attached : 

[floppy.org.uk-1576843353566.log](https://github.com/Floppy/scriptorum/files/3988211/floppy.org.uk-1576843353566.log)

[Stage of Pain 3.rosz.txt had to pretend it's a text file to upload here, rename back to .rosz to open](https://github.com/Floppy/scriptorum/files/3988212/Stage.of.Pain.3.rosz.txt)

**Comment by Floppy** [comment]
Thanks! I'll look into what's going on...

**Comment by Floppy** [comment]
Ah, I see this is an Astra Militarum team, which also had problems (reported in #9) because they seem to be missing some faction keywords. I've fixed that, and this file seems to work fine now.
